spring.application.name=electronics

spring.jpa.hibernate.ddl-auto = update
spring.datasource.url=jdbc:mysql://localhost:3306/mydatabase?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Rootpassword1.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql = true

server.port=8082

security.jwt.secret-key = qwfD3GHyM9+X2o4bJpQvYTd8sWlZ2kLgShz3T9pM1Gc=
security.jwt.expiration-time=300000

# Mail



adminEmail = david_dana17@yahoo.com
adminPassword = parolaAdmin1.