spring.application.name=hotelmanagement

spring.datasource.url=jdbc:mysql://localhost:3306/hotelDataBase?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Rootpassword1.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.url=jdbc:postgresql://dpg-d1e5f6re5dus739nsmgg-a.oregon-postgres.render.com:5432/hotel_management_sc6o?sslmode=require
#spring.datasource.username=hotel_management_sc6o_user
#spring.datasource.password=AtWK7FzMpEkykjyty3D6TOIcXyekeqmx
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

# Logging pentru SQL si conexiuni
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


server.port=8082

spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
logging.level.liquibase=DEBUG


# JWT secret key
security.jwt.secret-key = qwfD3GHyM9+X2o4bJpQvYTd8sWlZ2kLgShz3T9pM1Gc=
security.jwt.expiration-time=300000
#

booking.api.key = randomkeyforexternalbooking

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=danadavid1712@gmail.com
spring.mail.password=opie igwm kkna tehy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.devtools.restart.enabled=false

#Admin configuration
adminEmail = dana_david34@yahoo.com
adminPassword = parolaAdmin1.

spring.thymeleaf.check-template-location=false